name: Update Merged PRs

on:
  schedule:
    # Run at 00:00 every day
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Fetch PRs and update README
        env:
          GH_TOKEN: $\{{ secrets.GH_PAT }}
        run: |
          python scripts/update_prs.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: automated update of open source PRs" || exit 0
          git push
